/**
 * Unit tests for cameraCalibration.ts — camera calibration parsing + frustum geometry.
 *
 * Tests the pure math with mock calibration data and real Waymo fixtures.
 * Fixtures are generated by scripts/generate_fixtures.py.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { readFileSync, closeSync } from 'fs'
import { openSync, readSync, fstatSync } from 'fs'
import { resolve } from 'path'
import type { AsyncBuffer } from 'hyparquet'
import { openParquetFile, readAllRows } from '../parquet'
import {
  parseCameraCalibrations,
  buildFrustumLines,
  buildFrustumBase,
  buildFrustumEdges,
  type CameraCalib,
} from '../cameraCalibration'

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const FIXTURES = resolve(__dirname, '../../__fixtures__')
const SEGMENT_ID = 'mock_segment_0000'

function parquetPath(component: string): string {
  return resolve(FIXTURES, SEGMENT_ID, `${component}.parquet`)
}

const openFds: number[] = []

function nodeAsyncBuffer(filePath: string): AsyncBuffer {
  const buf = readFileSync(filePath)
  const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer
  return {
    byteLength: ab.byteLength,
    slice(start: number, end?: number): ArrayBuffer { return ab.slice(start, end) },
  }
}

afterAll(() => {
  for (const fd of openFds) {
    try { closeSync(fd) } catch { /* ignore */ }
  }
})

// ---------------------------------------------------------------------------
// Shared test data — loaded once from fixture
// ---------------------------------------------------------------------------

let calibMap: Map<number, CameraCalib>
let rawRows: Record<string, unknown>[]

beforeAll(async () => {
  const pf = await openParquetFile('camera_calibration', nodeAsyncBuffer(parquetPath('camera_calibration')))
  rawRows = await readAllRows(pf)
  calibMap = parseCameraCalibrations(rawRows)
})

// ---------------------------------------------------------------------------
// Tests: parseCameraCalibrations
// ---------------------------------------------------------------------------

describe('parseCameraCalibrations()', () => {
  it('returns 5 cameras from fixture data', () => {
    expect(calibMap.size).toBe(5)
    for (let i = 1; i <= 5; i++) {
      expect(calibMap.has(i)).toBe(true)
    }
  })

  it('each camera has correct image dimensions', () => {
    // Waymo: FRONT/FL/FR = 1920x1280, SL/SR = 1920x886
    const front = calibMap.get(1)!
    expect(front.width).toBe(1920)
    expect(front.height).toBe(1280)

    const sideLeft = calibMap.get(4)!
    expect(sideLeft.width).toBe(1920)
    expect(sideLeft.height).toBe(886)
  })

  it('FOV is within reasonable range (30°–120°)', () => {
    for (const [, calib] of calibMap) {
      const vFovDeg = calib.vFov * (180 / Math.PI)
      const hFovDeg = calib.hFov * (180 / Math.PI)
      expect(vFovDeg).toBeGreaterThan(20)
      expect(vFovDeg).toBeLessThan(120)
      expect(hFovDeg).toBeGreaterThan(20)
      expect(hFovDeg).toBeLessThan(120)
    }
  })

  it('FRONT camera has wider horizontal than vertical FOV', () => {
    const front = calibMap.get(1)!
    expect(front.hFov).toBeGreaterThan(front.vFov)
  })

  it('position is extracted from extrinsic matrix', () => {
    // Mock fixture uses identity extrinsics → position at origin
    for (const [, calib] of calibMap) {
      expect(calib.position.x).toBeCloseTo(0, 5)
      expect(calib.position.y).toBeCloseTo(0, 5)
      expect(calib.position.z).toBeCloseTo(0, 5)
    }
  })

  it('quaternion is a unit quaternion (length ≈ 1)', () => {
    for (const [, calib] of calibMap) {
      const len = calib.quaternion.length()
      expect(len).toBeCloseTo(1, 3)
    }
  })

  it('extrinsic is 16 elements (4x4 matrix)', () => {
    for (const [, calib] of calibMap) {
      expect(calib.extrinsic).toHaveLength(16)
    }
  })

  it('returns empty map for empty input', () => {
    const result = parseCameraCalibrations([])
    expect(result.size).toBe(0)
  })

  it('skips rows with missing camera_name', () => {
    const badRow = { '[CameraCalibrationComponent].width': 1920 } as Record<string, unknown>
    const result = parseCameraCalibrations([badRow])
    expect(result.size).toBe(0)
  })

  it('skips rows with missing intrinsics', () => {
    const badRow = {
      'key.camera_name': 1,
      '[CameraCalibrationComponent].width': 1920,
      '[CameraCalibrationComponent].height': 1280,
      // Missing f_u, f_v
    } as Record<string, unknown>
    const result = parseCameraCalibrations([badRow])
    expect(result.size).toBe(0)
  })
})

// ---------------------------------------------------------------------------
// Tests: FOV calculation
// ---------------------------------------------------------------------------

describe('FOV calculation', () => {
  it('vFov = 2 * atan(height / (2 * f_v))', () => {
    // Verify the math matches the formula directly
    const front = calibMap.get(1)!
    // Extract f_v from the raw fixture row
    const row = rawRows.find((r) => r['key.camera_name'] === 1)!
    const f_v = row['[CameraCalibrationComponent].intrinsic.f_v'] as number
    const expected = 2 * Math.atan(front.height / (2 * f_v))
    expect(front.vFov).toBeCloseTo(expected, 8)
  })

  it('hFov = 2 * atan(width / (2 * f_u))', () => {
    const front = calibMap.get(1)!
    const row = rawRows.find((r) => r['key.camera_name'] === 1)!
    const f_u = row['[CameraCalibrationComponent].intrinsic.f_u'] as number
    const expected = 2 * Math.atan(front.width / (2 * f_u))
    expect(front.hFov).toBeCloseTo(expected, 8)
  })
})

// ---------------------------------------------------------------------------
// Tests: Frustum geometry
// ---------------------------------------------------------------------------

describe('buildFrustumLines()', () => {
  it('produces 8 line segments (4 base + 4 edges) = 48 floats', () => {
    const lines = buildFrustumLines(Math.PI / 3, Math.PI / 4, 10)
    // 8 segments × 2 endpoints × 3 floats = 48
    expect(lines).toHaveLength(48)
  })

  it('all line start or end at origin for the 4 pyramid edges', () => {
    const lines = buildFrustumLines(Math.PI / 3, Math.PI / 4, 10)
    // Last 4 segments (indices 24..47) are origin→corner
    for (let i = 24; i < 48; i += 6) {
      expect(lines[i]).toBe(0)     // x
      expect(lines[i + 1]).toBe(0) // y
      expect(lines[i + 2]).toBe(0) // z
    }
  })

  it('far plane corners are at the correct depth', () => {
    const far = 15
    const lines = buildFrustumLines(Math.PI / 3, Math.PI / 4, far)
    // Base rectangle corners (first 4 segments) — z of each endpoint = far
    for (let i = 0; i < 24; i += 3) {
      expect(lines[i + 2]).toBeCloseTo(far, 5) // z = far for all base vertices
    }
  })
})

describe('buildFrustumBase()', () => {
  it('produces 4 line segments = 24 floats', () => {
    const base = buildFrustumBase(Math.PI / 3, Math.PI / 4, 10)
    expect(base).toHaveLength(24)
  })

  it('all Z coordinates equal far distance', () => {
    const far = 12
    const base = buildFrustumBase(Math.PI / 3, Math.PI / 4, far)
    for (let i = 2; i < 24; i += 3) {
      expect(base[i]).toBeCloseTo(far, 5)
    }
  })

  it('base width matches hFov at given distance', () => {
    const hFov = Math.PI / 3 // 60°
    const far = 10
    const base = buildFrustumBase(hFov, Math.PI / 4, far)
    const expectedHalfWidth = far * Math.tan(hFov / 2)
    // Collect unique X values from the base
    const xs = new Set<number>()
    for (let i = 0; i < 24; i += 3) {
      xs.add(Math.round(base[i] * 1000) / 1000)
    }
    const xArr = [...xs].sort((a, b) => a - b)
    expect(xArr[0]).toBeCloseTo(-expectedHalfWidth, 3)
    expect(xArr[xArr.length - 1]).toBeCloseTo(expectedHalfWidth, 3)
  })
})

describe('buildFrustumEdges()', () => {
  it('produces 4 line segments = 24 floats', () => {
    const edges = buildFrustumEdges(Math.PI / 3, Math.PI / 4, 10)
    expect(edges).toHaveLength(24)
  })

  it('each edge starts at origin', () => {
    const edges = buildFrustumEdges(Math.PI / 3, Math.PI / 4, 10)
    for (let i = 0; i < 24; i += 6) {
      expect(edges[i]).toBe(0)
      expect(edges[i + 1]).toBe(0)
      expect(edges[i + 2]).toBe(0)
    }
  })

  it('each edge ends at far distance', () => {
    const far = 8
    const edges = buildFrustumEdges(Math.PI / 3, Math.PI / 4, far)
    for (let i = 5; i < 24; i += 6) {
      expect(edges[i]).toBeCloseTo(far, 5)
    }
  })

  it('base + edges = lines (same geometry)', () => {
    const hFov = Math.PI / 3, vFov = Math.PI / 4, far = 10
    const full = buildFrustumLines(hFov, vFov, far)
    const base = buildFrustumBase(hFov, vFov, far)
    const edges = buildFrustumEdges(hFov, vFov, far)
    expect(full.length).toBe(base.length + edges.length)
    // Verify the combined data matches
    const combined = new Float32Array(base.length + edges.length)
    combined.set(base, 0)
    combined.set(edges, base.length)
    for (let i = 0; i < full.length; i++) {
      expect(full[i]).toBeCloseTo(combined[i], 5)
    }
  })
})
