/**
 * Unit tests for rangeImage.ts — range image → xyz conversion.
 *
 * Tests the pure math against mock Waymo v2.0 fixture data.
 * Fixtures are generated by scripts/generate_fixtures.py.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { readFileSync, closeSync } from 'fs'
import { openSync, readSync, fstatSync } from 'fs'
import { resolve } from 'path'
import type { AsyncBuffer } from 'hyparquet'
import { openParquetFile, readAllRows, readRowRange, isHeavyComponent } from '../parquet'
import {
  computeInclinations,
  computeAzimuths,
  convertRangeImageToPointCloud,
  convertAllSensors,
  parseLidarCalibration,
  POINT_STRIDE,
  type LidarCalibration,
  type RangeImage,
} from '../rangeImage'

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const FIXTURES = resolve(__dirname, '../../__fixtures__')
const SEGMENT_ID = 'mock_segment_0000'

function parquetPath(component: string): string {
  return resolve(FIXTURES, SEGMENT_ID, `${component}.parquet`)
}

const openFds: number[] = []

function nodeAsyncBuffer(filePath: string, lazy = false): AsyncBuffer {
  if (!lazy) {
    const buf = readFileSync(filePath)
    const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer
    return {
      byteLength: ab.byteLength,
      slice(start: number, end?: number): ArrayBuffer { return ab.slice(start, end) },
    }
  }
  const fd = openSync(filePath, 'r')
  openFds.push(fd)
  const { size } = fstatSync(fd)
  return {
    byteLength: size,
    slice(start: number, end?: number): ArrayBuffer {
      const length = (end ?? size) - start
      const buffer = Buffer.alloc(length)
      readSync(fd, buffer, 0, length, start)
      return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength)
    },
  }
}

afterAll(() => {
  for (const fd of openFds) {
    try { closeSync(fd) } catch { /* ignore */ }
  }
})

function openTestFile(component: string) {
  const lazy = isHeavyComponent(component)
  const buffer = nodeAsyncBuffer(parquetPath(component), lazy)
  return openParquetFile(component, buffer)
}

// ---------------------------------------------------------------------------
// Mock fixture dimensions (from scripts/generate_fixtures.py)
// TOP: 8×100, FRONT: 8×50, SIDE_L/R/REAR: 4×20
// ---------------------------------------------------------------------------

const MOCK_TOP_HEIGHT = 8
const MOCK_TOP_WIDTH = 100
const MOCK_FRONT_HEIGHT = 8
const MOCK_FRONT_WIDTH = 50

// ---------------------------------------------------------------------------
// Shared test data — loaded once
// ---------------------------------------------------------------------------

let calibrations: Map<number, LidarCalibration>
let topRangeImage: RangeImage
let frontRangeImage: RangeImage
let allRangeImages: Map<number, RangeImage>

beforeAll(async () => {
  // Load calibrations
  const calibPf = await openTestFile('lidar_calibration')
  const calibRows = await readAllRows(calibPf)
  calibrations = new Map()
  for (const row of calibRows) {
    const calib = parseLidarCalibration(row)
    calibrations.set(calib.laserName, calib)
  }

  // Load first frame's lidar data (5 sensors)
  const lidarPf = await openTestFile('lidar')
  const lidarRows = await readRowRange(lidarPf, 0, 5, [
    'key.laser_name',
    '[LiDARComponent].range_image_return1.shape',
    '[LiDARComponent].range_image_return1.values',
  ])

  allRangeImages = new Map()
  for (const row of lidarRows) {
    const laserName = row['key.laser_name'] as number
    const ri: RangeImage = {
      shape: row['[LiDARComponent].range_image_return1.shape'] as [number, number, number],
      values: row['[LiDARComponent].range_image_return1.values'] as number[],
    }
    allRangeImages.set(laserName, ri)
  }

  topRangeImage = allRangeImages.get(1)!
  frontRangeImage = allRangeImages.get(2)!
})

// ---------------------------------------------------------------------------
// Tests: Calibration parsing
// ---------------------------------------------------------------------------

describe('parseLidarCalibration()', () => {
  it('TOP has non-uniform inclinations', () => {
    const top = calibrations.get(1)!
    expect(top.beamInclinationValues).not.toBeNull()
    expect(top.beamInclinationValues!.length).toBe(MOCK_TOP_HEIGHT)
  })

  it('FRONT has uniform inclinations (null values)', () => {
    const front = calibrations.get(2)!
    expect(front.beamInclinationValues).toBeNull()
    expect(front.beamInclinationMin).toBeDefined()
    expect(front.beamInclinationMax).toBeDefined()
  })

  it('extrinsic is 4x4 matrix (16 elements)', () => {
    for (const [, calib] of calibrations) {
      expect(calib.extrinsic).toHaveLength(16)
    }
  })
})

// ---------------------------------------------------------------------------
// Tests: Angle computation
// ---------------------------------------------------------------------------

describe('computeInclinations()', () => {
  it('non-uniform: uses exact values for TOP', () => {
    const top = calibrations.get(1)!
    const inc = computeInclinations(MOCK_TOP_HEIGHT, top)
    expect(inc).toHaveLength(MOCK_TOP_HEIGHT)
    // Values are stored ascending (min→max); computeInclinations reverses to descending
    // So inc[0] = values[last] (max), inc[last] = values[0] (min)
    const last = MOCK_TOP_HEIGHT - 1
    expect(inc[0]).toBeCloseTo(top.beamInclinationValues![last], 5)
    expect(inc[last]).toBeCloseTo(top.beamInclinationValues![0], 5)
  })

  it('uniform: interpolates between min and max for FRONT', () => {
    const front = calibrations.get(2)!
    const inc = computeInclinations(MOCK_FRONT_HEIGHT, front)
    expect(inc).toHaveLength(MOCK_FRONT_HEIGHT)
    // Row 0 = max, last row = min
    expect(inc[0]).toBeCloseTo(front.beamInclinationMax, 5)
    expect(inc[MOCK_FRONT_HEIGHT - 1]).toBeCloseTo(front.beamInclinationMin, 5)
  })
})

describe('computeAzimuths()', () => {
  it('spans full 2π rotation', () => {
    const az = computeAzimuths(MOCK_TOP_WIDTH, 0)
    expect(az).toHaveLength(MOCK_TOP_WIDTH)
    // Range should be approximately [-π, π]
    const min = Math.min(...az)
    const max = Math.max(...az)
    // With 100 columns the discrete range is slightly less than full 2π
    expect(max - min).toBeCloseTo(2 * Math.PI, 0)
  })
})

// ---------------------------------------------------------------------------
// Tests: Single sensor conversion
// ---------------------------------------------------------------------------

describe('convertRangeImageToPointCloud()', () => {
  it('converts TOP lidar with reasonable point count', () => {
    const cloud = convertRangeImageToPointCloud(topRangeImage, calibrations.get(1)!)
    // Mock TOP: 8×100 = 800 pixels, ~88% valid → ~704 points
    const totalPixels = MOCK_TOP_HEIGHT * MOCK_TOP_WIDTH
    expect(cloud.pointCount).toBeGreaterThan(totalPixels * 0.7)
    expect(cloud.pointCount).toBeLessThanOrEqual(totalPixels)
    expect(cloud.positions.length).toBe(cloud.pointCount * POINT_STRIDE)
  })

  it('converts FRONT lidar with reasonable point count', () => {
    const cloud = convertRangeImageToPointCloud(frontRangeImage, calibrations.get(2)!)
    const totalPixels = MOCK_FRONT_HEIGHT * MOCK_FRONT_WIDTH
    expect(cloud.pointCount).toBeGreaterThan(0)
    expect(cloud.pointCount).toBeLessThanOrEqual(totalPixels)
  })

  it('output coordinates are in reasonable range (vehicle frame)', () => {
    const cloud = convertRangeImageToPointCloud(topRangeImage, calibrations.get(1)!)

    // Sample some points — should be within max range
    let maxDist = 0
    for (let i = 0; i < Math.min(cloud.pointCount, 1000); i++) {
      const x = cloud.positions[i * POINT_STRIDE]
      const y = cloud.positions[i * POINT_STRIDE + 1]
      const z = cloud.positions[i * POINT_STRIDE + 2]
      const dist = Math.sqrt(x * x + y * y + z * z)
      if (dist > maxDist) maxDist = dist
    }

    // Points should be within sensor range (mock ranges 5–70m)
    expect(maxDist).toBeGreaterThan(1) // not all at origin
    expect(maxDist).toBeLessThan(100)  // within reasonable range
  })

  it('z coordinates are reasonable for a car-mounted lidar', () => {
    const cloud = convertRangeImageToPointCloud(topRangeImage, calibrations.get(1)!)

    let minZ = Infinity, maxZ = -Infinity
    for (let i = 0; i < cloud.pointCount; i++) {
      const z = cloud.positions[i * POINT_STRIDE + 2]
      if (z < minZ) minZ = z
      if (z > maxZ) maxZ = z
    }

    // Mock extrinsic has Tz=1.8m offset, beam range [-0.29, 0.04] rad
    expect(minZ).toBeGreaterThan(-25)
    expect(maxZ).toBeLessThan(40)
  })

  it('intensity values are preserved', () => {
    const cloud = convertRangeImageToPointCloud(topRangeImage, calibrations.get(1)!)

    // At least some points should have non-zero intensity
    let hasNonZeroIntensity = false
    for (let i = 0; i < Math.min(cloud.pointCount, 100); i++) {
      if (cloud.positions[i * POINT_STRIDE + 3] > 0) {
        hasNonZeroIntensity = true
        break
      }
    }
    expect(hasNonZeroIntensity).toBe(true)
  })

  it('skips invalid pixels (range <= 0)', () => {
    // Create a synthetic range image with known invalid pixels
    const synthetic: RangeImage = {
      shape: [2, 3, 4],
      values: [
        // row 0: 3 pixels
        5.0, 0.5, 0, 0,   // valid
        -1,  0,   0, 0,   // invalid (range = -1)
        0,   0,   0, 0,   // invalid (range = 0)
        // row 1: 3 pixels
        10.0, 0.8, 0, 0,  // valid
        3.0,  0.2, 0, 0,  // valid
        -1,   0,   0, 0,  // invalid
      ],
    }

    const calib: LidarCalibration = {
      laserName: 99,
      extrinsic: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1], // identity
      beamInclinationValues: null,
      beamInclinationMin: -0.3,
      beamInclinationMax: 0.3,
    }

    const cloud = convertRangeImageToPointCloud(synthetic, calib)
    expect(cloud.pointCount).toBe(3) // only 3 valid pixels
  })
})

// ---------------------------------------------------------------------------
// Tests: Multi-sensor merge
// ---------------------------------------------------------------------------

describe('convertAllSensors()', () => {
  it('returns per-sensor clouds with correct total count', () => {
    const result = convertAllSensors(allRangeImages, calibrations)

    // Mock total: TOP(~704) + FRONT(~352) + 3×SIDE(~70×3=210) ≈ 1266 points
    expect(result.totalPointCount).toBeGreaterThan(800)
    expect(result.perSensor.size).toBe(5)
    // Verify totalPointCount matches sum of per-sensor counts
    let sum = 0
    for (const cloud of result.perSensor.values()) sum += cloud.pointCount
    expect(result.totalPointCount).toBe(sum)
  })

  it('all sensors combined have more points than any single sensor', () => {
    const result = convertAllSensors(allRangeImages, calibrations)
    const topOnly = convertRangeImageToPointCloud(topRangeImage, calibrations.get(1)!)

    expect(result.totalPointCount).toBeGreaterThan(topOnly.pointCount)
  })
})

// ---------------------------------------------------------------------------
// Tests: Edge cases
// ---------------------------------------------------------------------------

describe('edge cases', () => {
  it('all-invalid range image produces 0 points', () => {
    const allInvalid: RangeImage = {
      shape: [3, 4, 4],
      values: new Array(3 * 4 * 4).fill(0), // all range = 0 → invalid
    }
    const calib: LidarCalibration = {
      laserName: 99,
      extrinsic: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
      beamInclinationValues: null,
      beamInclinationMin: -0.3,
      beamInclinationMax: 0.3,
    }
    const cloud = convertRangeImageToPointCloud(allInvalid, calib)
    expect(cloud.pointCount).toBe(0)
    expect(cloud.positions.length).toBe(0)
  })

  it('single-pixel valid range image produces 1 point', () => {
    const singlePixel: RangeImage = {
      shape: [1, 1, 4],
      values: [10.0, 0.5, 0.1, 0], // range=10, intensity=0.5, elongation=0.1
    }
    const calib: LidarCalibration = {
      laserName: 99,
      extrinsic: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
      beamInclinationValues: null,
      beamInclinationMin: 0,
      beamInclinationMax: 0,
    }
    const cloud = convertRangeImageToPointCloud(singlePixel, calib)
    expect(cloud.pointCount).toBe(1)
    expect(cloud.positions.length).toBe(POINT_STRIDE)
    // With zero inclination and identity extrinsic, point should be on the XY plane
    const z = cloud.positions[2]
    expect(Math.abs(z)).toBeLessThan(0.01)
  })

  it('convertAllSensors with empty map returns 0 points', () => {
    const empty = new Map<number, RangeImage>()
    const result = convertAllSensors(empty, calibrations)
    expect(result.totalPointCount).toBe(0)
    expect(result.perSensor.size).toBe(0)
  })

  it('convertAllSensors with single sensor', () => {
    const single = new Map<number, RangeImage>()
    single.set(1, topRangeImage)
    const result = convertAllSensors(single, calibrations)
    expect(result.perSensor.size).toBe(1)
    expect(result.perSensor.has(1)).toBe(true)
    expect(result.totalPointCount).toBe(result.perSensor.get(1)!.pointCount)
  })

  it('convertAllSensors skips sensor without calibration', () => {
    const withUnknown = new Map<number, RangeImage>()
    withUnknown.set(1, topRangeImage) // has calibration
    withUnknown.set(99, topRangeImage) // no calibration for sensor 99
    const result = convertAllSensors(withUnknown, calibrations)
    // Should only have sensor 1 (sensor 99 silently skipped)
    expect(result.perSensor.has(1)).toBe(true)
    expect(result.perSensor.has(99)).toBe(false)
  })

  it('negative range values are filtered out', () => {
    const negRange: RangeImage = {
      shape: [2, 2, 4],
      values: [
        -5.0, 0.5, 0, 0,   // invalid (negative)
        -1.0, 0.5, 0, 0,   // invalid (negative)
        8.0,  0.5, 0, 0,   // valid
        -0.1, 0.5, 0, 0,   // invalid (negative)
      ],
    }
    const calib: LidarCalibration = {
      laserName: 99,
      extrinsic: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
      beamInclinationValues: null,
      beamInclinationMin: -0.1,
      beamInclinationMax: 0.1,
    }
    const cloud = convertRangeImageToPointCloud(negRange, calib)
    expect(cloud.pointCount).toBe(1)
  })

  it('output has no NaN or Infinity values', () => {
    const cloud = convertRangeImageToPointCloud(topRangeImage, calibrations.get(1)!)
    for (let i = 0; i < cloud.positions.length; i++) {
      expect(Number.isFinite(cloud.positions[i])).toBe(true)
    }
  })
})

// ---------------------------------------------------------------------------
// Export test data for GPU comparison tests
// ---------------------------------------------------------------------------

/**
 * Helper for GPU tests: returns the test data used in these CPU tests.
 * GPU tests import this to run the same assertions on GPU output.
 */
export function getTestData() {
  return { calibrations, topRangeImage, frontRangeImage, allRangeImages }
}
